eureka:
  instance:
    instance-id: config-client-${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone:
        http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka, http://eureka7003.com:7003/eureka
datasource:
   type: com.alibaba.druid.pool.DruidDataSource
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://127.0.0.1:3308/db2022?serverTimezone=UTC
   username: root
   password: bigdata

spring:
  application:
    name: config-client-service
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
    port: 5672
   
#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
 
