eureka:
  instance:
    instance-id: config-client-3355
    prefer-ip-address: true
  client:
    service-url:
      defaultZone:
        http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka, http://eureka7003.com:7003/eureka
